name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  # https://github.com/actions/setup-go/issues/491
  GOTOOLCHAIN: local

# From https://github.com/golangci/golangci-lint-action
jobs:
  golangci:
    permissions:
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '~1.24.1'
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '~1.24.1'
          check-latest: true
